name: Test AWS Secrets

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check secrets
        run: |
          if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
            echo "AWS_ACCESS_KEY_ID is EMPTY"
          else
            echo "AWS_ACCESS_KEY_ID exists"
          fi

          if [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
            echo "AWS_SECRET_ACCESS_KEY is EMPTY"
          else
            echo "AWS_SECRET_ACCESS_KEY exists"
          fi
